#######################
##### Build Image #####
#######################
FROM golang:1.19.3-alpine3.16 AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY *.go ./

RUN CGO_ENABLED=0 go build -o /cms-daq-simple-app


########################
### Production Image ###
########################
FROM scratch
WORKDIR /
COPY --from=build /cms-daq-simple-app /cms-daq-simple-app
EXPOSE 8080
CMD ["/cms-daq-simple-app"]
